Create Table EMPLOYEES22
(
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME NVARCHAR2(30),
LAST_NAME NVARCHAR2(30),
HIRE_DATE DATE,
JOB_ID NUMBER, CONSTRAINT fk_job_id
foreign key (JOB_ID)
references JOBS22(JOB_ID),
DEPARTMENT_ID NUMBER, CONSTRAINT fk_department
foreign key (DEPARTMENT_ID)
references Departments22(DEPARTMENT_ID)
);
CREATE TABLE DEPARTMENTS22
(
DEPARTMENT_ID NUMBER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(30),
LOCATION_ID NUMBER, CONSTRAINT fk_location_id
foreign key (LOCATION_ID)
references LOCATIONS22(LOCATION_ID)
);
CREATE TABLE JOBS22
(
JOB_ID NUMBER PRIMARY KEY,
JOB_TITLE VARCHAR2(30)
);
CREATE TABLE LOCATIONS22
(
LOCATION_ID NUMBER PRIMARY KEY,
LOCATION_NAME VARCHAR2(30)
);
INSERT INTO EMPLOYEES22 VALUES (1, 'JOHN', 'SMITH', SYSDATE, 75, 24);
COMMIT;
INSERT INTO DEPARTMENTS22 VALUES(24, 'Something', 55);
INSERT INTO JOBS22 VALUES(75, 'Programmer');
INSERT INTO LOCATIONS22 VALUES(55, 'New York');
COMMIT;

ALTER TABLE EMPLOYEES22
ADD CONSTRAINT fk_department
foreign key (DEPARTMENT_ID)
references Departments22(DEPARTMENT_ID);

DROP TABLE EMPLOYEES22;
DROP TABLE DEPARTMENTS22;
DROP TABLE JOBS22;
DROP TABLE LOCATIONS22;


CREATE OR REPLACE PROCEDURE CRUD(cr out sys_refcursor) AS
Begin
OPEN cr FOR
SELECT * FROM EMPLOYEES22 
                    INNER JOIN DEPARTMENTS22 using(department_id)
                    INNER JOIN JOBS22 using(job_id)
                    INNER JOIN LOCATIONS22 using(location_id) ORDER BY(EMPLOYEE_ID);

END CRUD;


CREATE OR REPLACE PROCEDURE INS (EID IN NUMBER, F_N IN VARCHAR2, L_N IN VARCHAR2, HD IN DATE, JID IN NUMBER, DID IN NUMBER,
D_N IN VARCHAR2, LID IN NUMBER, LOC_N IN VARCHAR2, J_T IN VARCHAR2) AS
BEGIN
INSERT INTO LOCATIONS22 VALUES(LID, LOC_N);
INSERT INTO JOBS22 VALUES(JID, J_T);
INSERT INTO DEPARTMENTS22 VALUES(DID, D_N ,LID);
INSERT INTO EMPLOYEES22 VALUES(EID, F_N, L_N, HD, JID, DID);
END INS;


CREATE OR REPLACE PROCEDURE UPD (EID IN NUMBER, F_N IN VARCHAR2, L_N IN VARCHAR2, HD IN DATE, JID IN NUMBER, DID IN NUMBER,
D_N IN VARCHAR2, LID IN NUMBER, LOC_N IN VARCHAR2, J_T IN VARCHAR2) AS
BEGIN
UPDATE LOCATIONS22 SET LOCATION_NAME = LOC_N WHERE LOCATION_ID = (SELECT LOCATION_ID FROM DEPARTMENTS22 WHERE DEPARTMENT_ID = DID);
UPDATE JOBS22 SET JOB_TITLE = J_T WHERE JOB_ID = (SELECT JOB_ID FROM EMPLOYEES22 WHERE EMPLOYEE_ID = EID);
UPDATE DEPARTMENTS22 SET DEPARTMENT_NAME = D_N, LOCATION_ID = LID WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES22 WHERE EMPLOYEE_ID = EID);
UPDATE EMPLOYEES22 SET FIRST_NAME = F_N, LAST_NAME = L_N, HIRE_DATE = HD, JOB_ID = JID WHERE EMPLOYEE_ID = EID;
END UPD;


CREATE OR REPLACE PROCEDURE DELT (EID IN NUMBER) AS
BEGIN
DELETE FROM EMPLOYEES22 WHERE EMPLOYEE_ID = EID;
END DELT;